language: ruby
rvm:
  - 1.9.3
  - 2.2.2
  - 2.4.1
  - ruby-head
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
install: "bundle install --jobs 8"
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rspec
gemfile:
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails50.gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/rails42.gemfile
    - rvm: 2.4.1
      gemfile: gemfiles/rails42.gemfile
    - rvm: ruby-head
      gemfile: gemfiles/rails42.gemfile
  allow_failures:
    - rvm: ruby-head
